---
apiVersion: v1
kind: Secret
metadata:
  name: hp-wad01-poi-backend-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/rosa916-rvhvd/hp-wad01-backend-gitops
